#!/bin/bash
#
# Standalone script to update the service to latest
#
# best to add the following to /etc/hosts
# 143.110.213.234 repo.sofvie.com

export DOCKER_BUILDKIT=1

CURR=$(pwd)
SERVICE=`basename $(pwd)`
SRC=/home/edwinperez/SofvieMasterCode/$SERVICE
# SRC=/home/aprowse/Clients/Sofvie/source/$SERVICE
BRANCH=`git branch --show-current | cut -d"-" -f1`
FILE=$SERVICE-$BRANCH.tar.gz
CURRVER=`grep FROM Dockerfile.update | grep -o '[^-]*$'`
NEXTVER=$((CURRVER+1))
IMAGE=repo.sofvie.com:5000/$BRANCH:$SERVICE-$NEXTVER

# update source
cd $SRC
git checkout releases/$BRANCH
git pull
cd APP

tar czf $CURR/data/$FILE \
  --exclude=".git" --exclude=".gitignore" * .[a-z,A-Z]* > /dev/null 2>&1

cd $CURR

ARCH=`uname -p`
case $ARCH in
  arm ) BUILD="buildx build --platform linux/amd64"
        SED="sed -i -bk";;
  *   ) BUILD="build"
        SED="sed -i";;
esac

docker $BUILD -t $IMAGE -f $CURR/Dockerfile.update .
docker push $IMAGE

# edit the Dockerfile FROM statement, base image build on the current release
sed -i "s,^FROM.*,FROM $IMAGE,g" Dockerfile.update

printf "\n\nthe new image is \e[1m$IMAGE\e[0m\n"
printf "\n1. Update the baseclient k8s/$SERVICE.yaml file image: line with:"
printf "\n   image: $IMAGE"
printf "\n2. run upgrade\n\n"
