FROM repo.sofvie.com:5000/1.3.5.2:api-2

WORKDIR $API
ADD data/api-1.3.5.2.tar.gz .

RUN sed -i 's/^    host:.*/    host: "db",/g' apps/language/api/views/translationimportutility3.0.js

# for schedule_report.py when devs push prod code
# RUN sed -i 's,with open.*,with open("/opt/api/sofvie_api/.env") as f:,g' /opt/api/schedule_report.py \
COPY data/schedule_report.py $API/
RUN chmod +x $API/schedule_report.py
