#!/bin/bash
#
# Standalone script to update the service to latest
#
# best to add the following to /etc/hosts
# 143.110.213.234 repo.sofvie.com

export DOCKER_BUILDKIT=1

SERVICE=`basename $(pwd)`
BRANCH=database
CURRVER=`awk -F '"' '/version/{ print $2}' Dockerfile`
NEXTVER=$((CURRVER+1))
IMAGE=repo.sofvie.com:5000/$BRANCH:$SERVICE-$NEXTVER

ARCH=`uname -p`
case $ARCH in
  arm ) BUILD="buildx build --platform linux/amd64"
        SED="sed -i -bk";;
  *   ) BUILD="build"
        SED="sed -i";;
esac

docker $BUILD -t $IMAGE -f Dockerfile .
docker push $IMAGE

# edit the Dockerfile FROM statement, base image build on the current release
$SED "s/^LABEL version.*/LABEL version=\"$NEXTVER\"/g" Dockerfile
rm *-bk 2> /dev/null

printf "\n\nthe new image is \e[1m$IMAGE\e[0m\n"
printf "\n1. Update the baseclient k8s/$SERVICE.yaml file image: line with:"
printf "\n   image: $IMAGE"
printf "\n2. run upgrade\n\n"
